### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by TheyCallMeJQ** [christian-plourde/COMP-476-Project#1]
We need a grid system; I'll spend some time on this today.
In essence, we just need a system which divides a plane into a square grid space, where we'll later be able place things. For now, I'll represent these squares as a Gizmo.

**Comment by christian-plourde** [comment]
I am currently working on a graph. We can test our structures together to make sure they work well together

**Comment by TheyCallMeJQ** [comment]
Dammit I just saw this
