### ISSUE TITLE
DT: Enemy chases and pushes player endlessly

### ISSUE THREAD

**Issue by TheyCallMeJQ** [christian-plourde/COMP-476-Project#29]
At the moment, if the enemy spots the player, the enemy will just chase endlessly, and push the player about the scene. Possible fix: make the enemy max velocity proportional to the player's current velocity?

**Comment by christian-plourde** [comment]
This is happening because the arrival radius is too small. the arrival radius should be larger when the enemy goes to the player. for nodes the arrival radius must be small. I'm fixing this now.

**Comment by christian-plourde** [comment]
Fixed by picking a point slightly in front of player as movement target
