### ISSUE TITLE
Enemy Orientation on player chase

### ISSUE THREAD

**Issue by TheyCallMeJQ** [christian-plourde/COMP-476-Project#32]
The enemy isn't able to make a full counter-clockwise rotation when chasing the player. Eventually, it's spin-to-win.

**Comment by christian-plourde** [comment]
I don't think i can fix this. this was the issue sam and i were working on when the wolf goes "up". We've looked at this a lot in the past and have not been able to find a solution (it's never a full spin though) so not such a huge deal).

**Comment by TheyCallMeJQ** [comment]
Genuinely I think we should find a solution for this somehow, because the thing is when the wolf does his little pirouette, he no longer sees the player, and so the entire behaviour changes. Maybe when the angle goes past a certain limit, we can set the direction with Rotation.LookAt, and sort of reinitialize the rotation we're keeping track of, with angular velocity, and all that?

**Comment by TheyCallMeJQ** [comment]
Worst case, maybe the "last saw player" behaviour we discussed recently can maybe compensate for this
